package co.approbe.core.movement.dao;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "movements")
public class Movements {
	
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String id;
	@DynamoDBAttribute
	private String numberId;
	@DynamoDBAttribute
	private String dateMovement;
	@DynamoDBAttribute
	private String typeMovement;
	@DynamoDBAttribute
	private String description;
	@DynamoDBAttribute
	private String value;
	@DynamoDBAttribute
	private String product;
	@DynamoDBAttribute
	private String account;
	@DynamoDBAttribute
	private String status;
	@DynamoDBAttribute
	private String origenAccount;
	@DynamoDBAttribute
	private String destinationAccountId;
	@DynamoDBAttribute
	private String origenAccountId;
	
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getNumberId() {
		return numberId;
	}
	public void setNumberId(String numberId) {
		this.numberId = numberId;
	}
	public String getDateMovement() {
		return dateMovement;
	}
	public void setDateMovement(String dateMovement) {
		this.dateMovement = dateMovement;
	}
	public String getTypeMovement() {
		return typeMovement;
	}
	public void setTypeMovement(String typeMovement) {
		this.typeMovement = typeMovement;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public String getValue() {
		return value;
	}
	public void setValue(String value) {
		this.value = value;
	}
	public String getProduct() {
		return product;
	}
	public void setProduct(String product) {
		this.product = product;
	}
	public String getAccount() {
		return account;
	}
	public void setAccount(String account) {
		this.account = account;
	}
	public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status;
	}
	public String getOrigenAccount() {
		return origenAccount;
	}
	public void setOrigenAccount(String origenAccount) {
		this.origenAccount = origenAccount;
	}
	public String getDestinationAccountId() {
		return destinationAccountId;
	}
	public void setDestinationAccountId(String destinationAccountId) {
		this.destinationAccountId = destinationAccountId;
	}
	public String getOrigenAccountId() {
		return origenAccountId;
	}
	public void setOrigenAccountId(String origenAccountId) {
		this.origenAccountId = origenAccountId;
	}
	public Movements(String id, String numberId, String dateMovement, String typeMovement, String description,
			String value, String product, String account, String status, String origenAccount,
			String destinationAccountId, String origenAccountId) {
		super();
		this.id = id;
		this.numberId = numberId;
		this.dateMovement = dateMovement;
		this.typeMovement = typeMovement;
		this.description = description;
		this.value = value;
		this.product = product;
		this.account = account;
		this.status = status;
		this.origenAccount = origenAccount;
		this.destinationAccountId = destinationAccountId;
		this.origenAccountId = origenAccountId;
	}
	public Movements() {
		super();
		// TODO Auto-generated constructor stub
	}
	@Override
	public String toString() {
		return "{\"id\":\"" + id + "\", \"numberId\":\"" + numberId + "\", \"dateMovement\":\"" + dateMovement
				+ "\", \"typeMovement\":\"" + typeMovement + "\", \"description\":\"" + description + "\", \"value\":\""
				+ value + "\", \"product\":\"" + product + "\", \"account\":\"" + account + "\", \"status\":\"" + status
				+ "\", \"origenAccount\":\"" + origenAccount + "\", \"destinationAccountId\":\"" + destinationAccountId
				+ "\", \"origenAccountId\":\"" + origenAccountId + "\"}";
	}
	
	
	
}
