package co.approbe.consult.account;

import java.time.LocalDateTime;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "associateLoan")
public class AssociateLoan {
	@DynamoDBAttribute
	@DynamoDBAutoGeneratedKey
	private String id;
	@DynamoDBAttribute
	private String identificationType;
	@DynamoDBHashKey
	private String numberIdInvestor;
	@DynamoDBAttribute
	private String numberIdBorrower;
	@DynamoDBAttribute
	private int value;
	@DynamoDBAttribute
	private int rate;
	@DynamoDBAttribute
	private int fees;
	@DynamoDBAttribute
	private int profit;
	@DynamoDBAttribute
	private int active;
	@DynamoDBAttribute
	private String description;
	LocalDateTime dateTime = LocalDateTime.now(ZoneOffset.of("-05:00"));
	DateTimeFormatter dtformat = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
	@DynamoDBAttribute
	private String dateSaveBD = dateTime.format(dtformat);
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getIdentificationType() {
		return identificationType;
	}
	public void setIdentificationType(String identificationType) {
		this.identificationType = identificationType;
	}
	public String getNumberIdInvestor() {
		return numberIdInvestor;
	}
	public void setNumberIdInvestor(String numberIdInvestor) {
		this.numberIdInvestor = numberIdInvestor;
	}
	public String getNumberIdBorrower() {
		return numberIdBorrower;
	}
	public void setNumberIdBorrower(String numberIdBorrower) {
		this.numberIdBorrower = numberIdBorrower;
	}
	public int getValue() {
		return value;
	}
	public void setValue(int value) {
		this.value = value;
	}
	public int getRate() {
		return rate;
	}
	public void setRate(int rate) {
		this.rate = rate;
	}
	public int getFees() {
		return fees;
	}
	public void setFees(int fees) {
		this.fees = fees;
	}
	public int getActive() {
		return active;
	}
	public void setActive(int active) {
		this.active = active;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public String getDateSaveBD() {
		return dateSaveBD;
	}
	public void setDateSaveBD(String dateSaveBD) {
		this.dateSaveBD = dateSaveBD;
	}
	public int getProfit() {
		return profit;
	}
	public void setProfit(int profit) {
		this.profit = profit;
	}
	public AssociateLoan(String id, String identificationType, String numberIdInvestor, String numberIdBorrower,
			int value, int rate, int fees, int profit, int active, String description, String dateSaveBD) {
		super();
		this.id = id;
		this.identificationType = identificationType;
		this.numberIdInvestor = numberIdInvestor;
		this.numberIdBorrower = numberIdBorrower;
		this.value = value;
		this.rate = rate;
		this.fees = fees;
		this.profit = profit;
		this.active = active;
		this.description = description;
		this.dateSaveBD = dateSaveBD;
	}
	public AssociateLoan() {
		super();
	}
	@Override
	public String toString() {
		return "AssociateLoan [id=" + id + ", identificationType=" + identificationType + ", numberIdInvestor="
				+ numberIdInvestor + ", numberIdBorrower=" + numberIdBorrower + ", value=" + value + ", rate=" + rate
				+ ", fees=" + fees + ", profit=" + profit + ", active=" + active + ", description=" + description
				+ ", dateSaveBD=" + dateSaveBD + "]";
	}
	
	
	
}
