package co.approbe.create.pdf;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
@DynamoDBTable(tableName = "award")
public class Award {
	
		@DynamoDBAttribute
		@DynamoDBAutoGeneratedKey
		private String id;
		@DynamoDBAttribute
		private String identification;
		@DynamoDBHashKey
		private String numberId;
		@DynamoDBAttribute
		private String cognitoId;
		@DynamoDBAttribute
		private String expeditionDate;
		@DynamoDBAttribute
		private String names;
		@DynamoDBAttribute
		private String lastName;
		@DynamoDBAttribute
		private String cellphone;
		@DynamoDBAttribute
		private String gender;
		@DynamoDBAttribute
		private String email;
		public String getId() {
			return id;
		}
		public void setId(String id) {
			this.id = id;
		}
		public String getIdentification() {
			return identification;
		}
		public void setIdentification(String identification) {
			this.identification = identification;
		}
		public String getNumberId() {
			return numberId;
		}
		public void setNumberId(String numberId) {
			this.numberId = numberId;
		}
		public String getCognitoId() {
			return cognitoId;
		}
		public void setCognitoId(String cognitoId) {
			this.cognitoId = cognitoId;
		}
		public String getExpeditionDate() {
			return expeditionDate;
		}
		public void setExpeditionDate(String expeditionDate) {
			this.expeditionDate = expeditionDate;
		}
		public String getNames() {
			return names;
		}
		public void setNames(String names) {
			this.names = names;
		}
		public String getLastName() {
			return lastName;
		}
		public void setLastName(String lastName) {
			this.lastName = lastName;
		}
		public String getCellphone() {
			return cellphone;
		}
		public void setCellphone(String cellphone) {
			this.cellphone = cellphone;
		}
		public String getGender() {
			return gender;
		}
		public void setGender(String gender) {
			this.gender = gender;
		}
		public String getEmail() {
			return email;
		}
		public void setEmail(String email) {
			this.email = email;
		}
		public Award(String id, String identification, String numberId, String cognitoId, String expeditionDate,
				String names, String lastName, String cellphone, String gender, String email) {
			super();
			this.id = id;
			this.identification = identification;
			this.numberId = numberId;
			this.cognitoId = cognitoId;
			this.expeditionDate = expeditionDate;
			this.names = names;
			this.lastName = lastName;
			this.cellphone = cellphone;
			this.gender = gender;
			this.email = email;
		}
		public Award() {
			super();
		}
		
}
