package co.approbe.autentic;

import java.time.LocalDateTime;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="docsSignature")
public class DocsUser {
		@DynamoDBHashKey
		private String id;
		@DynamoDBAttribute
		private String numberId;
		@DynamoDBAttribute
		private String codeFirmDocs;
		@DynamoDBAttribute
		private String urlAuthorizationBorrower;
		@DynamoDBAttribute
		private String urlAuthorizationAward;
		@DynamoDBAttribute
		private String urlContractAward;
		@DynamoDBAttribute
		private String urlMutualContract;		
		@DynamoDBAttribute
		private String urlPower;
		 @DynamoDBAttribute
		private String urlPromissory;
		@DynamoDBAttribute
		private String codeTx;
		@DynamoDBAttribute
		private String codeFirmDocsAuthorizationBorrower;
		@DynamoDBAttribute
		private String codeFirmDocsAuthorizationAward;
		@DynamoDBAttribute
		private String codeFirmDocsContractAward;
		@DynamoDBAttribute
		private String codeFirmDocsMutualContract;
		@DynamoDBAttribute
		private String codeFirmDocsPromissory;
		@DynamoDBAttribute
		private String codeFirmDocsPower;
		@DynamoDBAttribute
		private String fileIdAuthorizationBorrower;
		@DynamoDBAttribute
		private String fileIdAuthorizationAward;
		@DynamoDBAttribute
		private String fileIdContractAward;
		@DynamoDBAttribute
		private String fileIdMutualContract;
		@DynamoDBAttribute
		private String fileIdPromissory;
		@DynamoDBAttribute
		private String fileIdPower;
		
		LocalDateTime dateTime = LocalDateTime.now(ZoneOffset.of("-05:00"));
		DateTimeFormatter dtformat = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
		@DynamoDBAttribute
		private String dateSave = dateTime.format(dtformat);
		
		
		public String getNumberId() {
			return numberId;
		}


		public void setNumberId(String numberId) {
			this.numberId = numberId;
		}


		public String getUrlAuthorizationBorrower() {
			return urlAuthorizationBorrower;
		}


		public void setUrlAuthorizationBorrower(String urlAuthorizationBorrower) {
			this.urlAuthorizationBorrower = urlAuthorizationBorrower;
		}


		public String getUrlAuthorizationAward() {
			return urlAuthorizationAward;
		}


		public void setUrlAuthorizationAward(String urlAuthorizationAward) {
			this.urlAuthorizationAward = urlAuthorizationAward;
		}


		public String getUrlContractAward() {
			return urlContractAward;
		}


		public void setUrlContractAward(String urlContractAward) {
			this.urlContractAward = urlContractAward;
		}


		public String getUrlMutualContract() {
			return urlMutualContract;
		}


		public void setUrlMutualContract(String urlMutualContract) {
			this.urlMutualContract = urlMutualContract;
		}


		public String getUrlPower() {
			return urlPower;
		}


		public void setUrlPower(String urlPower) {
			this.urlPower = urlPower;
		}


		public String getUrlPromissory() {
			return urlPromissory;
		}


		public void setUrlPromissory(String urlPromissory) {
			this.urlPromissory = urlPromissory;
		}


		public String getDateSave() {
			return dateSave;
		}


		public void setDateSave(String dateSave) {
			this.dateSave = dateSave;
		}


		public String getCodeFirmDocs() {
			return codeFirmDocs;
		}


		public void setCodeFirmDocs(String codeFirmDocs) {
			this.codeFirmDocs = codeFirmDocs;
		}


		public String getCodeTx() {
			return codeTx;
		}


		public void setCodeTx(String codeTx) {
			this.codeTx = codeTx;
		}


		public String getCodeFirmDocsAuthorizationBorrower() {
			return codeFirmDocsAuthorizationBorrower;
		}


		public void setCodeFirmDocsAuthorizationBorrower(String codeFirmDocsAuthorizationBorrower) {
			this.codeFirmDocsAuthorizationBorrower = codeFirmDocsAuthorizationBorrower;
		}


		public String getCodeFirmDocsAuthorizationAward() {
			return codeFirmDocsAuthorizationAward;
		}


		public void setCodeFirmDocsAuthorizationAward(String codeFirmDocsAuthorizationAward) {
			this.codeFirmDocsAuthorizationAward = codeFirmDocsAuthorizationAward;
		}


		public String getCodeFirmDocsContractAward() {
			return codeFirmDocsContractAward;
		}


		public void setCodeFirmDocsContractAward(String codeFirmDocsContractAward) {
			this.codeFirmDocsContractAward = codeFirmDocsContractAward;
		}


		public String getCodeFirmDocsMutualContract() {
			return codeFirmDocsMutualContract;
		}


		public void setCodeFirmDocsMutualContract(String codeFirmDocsMutualContract) {
			this.codeFirmDocsMutualContract = codeFirmDocsMutualContract;
		}


		public String getCodeFirmDocsPromissory() {
			return codeFirmDocsPromissory;
		}


		public void setCodeFirmDocsPromissory(String codeFirmDocsPromissory) {
			this.codeFirmDocsPromissory = codeFirmDocsPromissory;
		}


		public String getCodeFirmDocsPower() {
			return codeFirmDocsPower;
		}


		public void setCodeFirmDocsPower(String codeFirmDocsPower) {
			this.codeFirmDocsPower = codeFirmDocsPower;
		}


		public String getFileIdAuthorizationBorrower() {
			return fileIdAuthorizationBorrower;
		}


		public void setFileIdAuthorizationBorrower(String fileIdAuthorizationBorrower) {
			this.fileIdAuthorizationBorrower = fileIdAuthorizationBorrower;
		}


		public String getFileIdAuthorizationAward() {
			return fileIdAuthorizationAward;
		}


		public void setFileIdAuthorizationAward(String fileIdAuthorizationAward) {
			this.fileIdAuthorizationAward = fileIdAuthorizationAward;
		}


		public String getFileIdContractAward() {
			return fileIdContractAward;
		}


		public void setFileIdContractAward(String fileIdContractAward) {
			this.fileIdContractAward = fileIdContractAward;
		}


		public String getFileIdMutualContract() {
			return fileIdMutualContract;
		}


		public void setFileIdMutualContract(String fileIdMutualContract) {
			this.fileIdMutualContract = fileIdMutualContract;
		}


		public String getFileIdPromissory() {
			return fileIdPromissory;
		}


		public void setFileIdPromissory(String fileIdPromissory) {
			this.fileIdPromissory = fileIdPromissory;
		}


		public String getFileIdPower() {
			return fileIdPower;
		}


		public void setFileIdPower(String fileIdPower) {
			this.fileIdPower = fileIdPower;
		}
		
		


		public String getId() {
			return id;
		}


		public void setId(String id) {
			this.id = id;
		}


		public DocsUser() {
			super();
		}


		public DocsUser(String id, String numberId, String codeFirmDocs, String urlAuthorizationBorrower,
				String urlAuthorizationAward, String urlContractAward, String urlMutualContract, String urlPower,
				String urlPromissory, String codeTx, String codeFirmDocsAuthorizationBorrower,
				String codeFirmDocsAuthorizationAward, String codeFirmDocsContractAward,
				String codeFirmDocsMutualContract, String codeFirmDocsPromissory, String codeFirmDocsPower,
				String fileIdAuthorizationBorrower, String fileIdAuthorizationAward, String fileIdContractAward,
				String fileIdMutualContract, String fileIdPromissory, String fileIdPower, String dateSave) {
			super();
			this.id = id;
			this.numberId = numberId;
			this.codeFirmDocs = codeFirmDocs;
			this.urlAuthorizationBorrower = urlAuthorizationBorrower;
			this.urlAuthorizationAward = urlAuthorizationAward;
			this.urlContractAward = urlContractAward;
			this.urlMutualContract = urlMutualContract;
			this.urlPower = urlPower;
			this.urlPromissory = urlPromissory;
			this.codeTx = codeTx;
			this.codeFirmDocsAuthorizationBorrower = codeFirmDocsAuthorizationBorrower;
			this.codeFirmDocsAuthorizationAward = codeFirmDocsAuthorizationAward;
			this.codeFirmDocsContractAward = codeFirmDocsContractAward;
			this.codeFirmDocsMutualContract = codeFirmDocsMutualContract;
			this.codeFirmDocsPromissory = codeFirmDocsPromissory;
			this.codeFirmDocsPower = codeFirmDocsPower;
			this.fileIdAuthorizationBorrower = fileIdAuthorizationBorrower;
			this.fileIdAuthorizationAward = fileIdAuthorizationAward;
			this.fileIdContractAward = fileIdContractAward;
			this.fileIdMutualContract = fileIdMutualContract;
			this.fileIdPromissory = fileIdPromissory;
			this.fileIdPower = fileIdPower;
			this.dateSave = dateSave;
		}

		

		
}
