package co.approbe.authorization;

import java.time.LocalDateTime;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "logsAuthorizationData")
public class Logs {
	
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String id;
	
	@DynamoDBAttribute
	private String logs;
	
	@DynamoDBAttribute
	private String numberId;
	
	LocalDateTime dateTime = LocalDateTime.now(ZoneOffset.of("-05:00"));
	DateTimeFormatter dtformat = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
	@DynamoDBAttribute
	private String dateSave = dateTime.format(dtformat);
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getLogs() {
		return logs;
	}
	public void setLogs(String logs) {
		this.logs = logs;
	}
	public String getNumberId() {
		return numberId;
	}
	public void setNumberId(String numberId) {
		this.numberId = numberId;
	}
	public String getDateSave() {
		return dateSave;
	}
	public void setDateSave(String dateSave) {
		this.dateSave = dateSave;
	}
	public Logs(String id, String logs, String numberId, String dateSave) {
		super();
		this.id = id;
		this.logs = logs;
		this.numberId = numberId;
		this.dateSave = dateSave;
	}
	@Override
	public String toString() {
		return "{\"id\":\"" + id + "\", \"logs\":\"" + logs + "\", \"numberId\":\"" + numberId + "\", \"dateSave\":\""
				+ dateSave + "\"}";
	}
	public Logs() {
		super();
		// TODO Auto-generated constructor stub
	}
	
	
	
}
