package co.approbe.award.lambda;

import java.time.LocalDateTime;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedJson;

@DynamoDBTable(tableName = "award")
public class BasicInformation {
	@DynamoDBAttribute
	@DynamoDBAutoGeneratedKey
	private String id;
	@DynamoDBAttribute
	private String identification;
	@DynamoDBHashKey
	private String numberId;
	@DynamoDBAttribute
	private String cognitoId;
	@DynamoDBAttribute
	private String expeditionDate;
	@DynamoDBAttribute
	private String names;
	@DynamoDBAttribute
	private String lastName;
	@DynamoDBAttribute
	private String cellphone;
	@DynamoDBAttribute
	private String gender;
	@DynamoDBAttribute
	private String email;
	@DynamoDBAttribute
	private int habeas;
	@DynamoDBAttribute
	private int tyc;
	@DynamoDBAttribute
	private String signature;

	@DynamoDBTypeConvertedJson
	private GeneralInformation generalInformation;
	@DynamoDBTypeConvertedJson
	private EconomicActivity economicActivity;
	
	@DynamoDBTypeConvertedJson
	private FinancialInformation financialInformation;
	@DynamoDBTypeConvertedJson
	private PEP pep;
	@DynamoDBTypeConvertedJson
	private Authorization authorization;

	@DynamoDBAttribute
	private int active;
	@DynamoDBAttribute
	private String description;
	@DynamoDBAttribute
	private String notice;
	LocalDateTime dateTime = LocalDateTime.now(ZoneOffset.of("-05:00"));
	DateTimeFormatter dtformat = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
	@DynamoDBAttribute
	private String dateSave = dateTime.format(dtformat);



	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getIdentification() {
		return identification;
	}

	public void setIdentification(String identification) {
		this.identification = identification;
	}

	public String getNumberId() {
		return numberId;
	}

	public void setNumberId(String numberId) {
		this.numberId = numberId;
	}

	public String getExpeditionDate() {
		return expeditionDate;
	}

	public void setExpeditionDate(String expeditionDate) {
		this.expeditionDate = expeditionDate;
	}

	public String getNames() {
		return names;
	}

	public void setNames(String names) {
		this.names = names;
	}

	public String getCellphone() {
		return cellphone;
	}

	public void setCellphone(String cellphone) {
		this.cellphone = cellphone;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public int getHabeas() {
		return habeas;
	}

	public void setHabeas(int habeas) {
		this.habeas = habeas;
	}

	public int getTyc() {
		return tyc;
	}

	public void setTyc(int tyc) {
		this.tyc = tyc;
	}

	public String getSignature() {
		return signature;
	}

	public void setSignature(String signature) {
		this.signature = signature;
	}

	public GeneralInformation getGeneralInformation() {
		return generalInformation;
	}

	public void setGeneralInformation(GeneralInformation generalInformation) {
		this.generalInformation = generalInformation;
	}

	public EconomicActivity getEconomicActivity() {
		return economicActivity;
	}

	public void setEconomicActivity(EconomicActivity economicActivity) {
		this.economicActivity = economicActivity;
	}

	public FinancialInformation getFinancialInformation() {
		return financialInformation;
	}

	public void setFinancialInformation(FinancialInformation financialInformation) {
		this.financialInformation = financialInformation;
	}

	public PEP getPep() {
		return pep;
	}

	public void setPep(PEP pep) {
		this.pep = pep;
	}

	public Authorization getAuthorization() {
		return authorization;
	}

	public void setAuthorization(Authorization authorization) {
		this.authorization = authorization;
	}

	public int getActive() {
		return active;
	}

	public void setActive(int active) {
		this.active = active;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getDateSave() {
		return dateSave;
	}

	public void setDateSave(String dateSave) {
		this.dateSave = dateSave;
	}

	public String getNotice() {
		return notice;
	}

	public void setNotice(String notice) {
		this.notice = notice;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getCognitoId() {
		return cognitoId;
	}

	public void setCognitoId(String cognitoId) {
		this.cognitoId = cognitoId;
	}

	public BasicInformation() {
		super();
	}

	public BasicInformation(String id, String identification, String numberId, String cognitoId, String expeditionDate,
			String names, String lastName, String cellphone, String gender, String email, int habeas, int tyc,
			String signature, GeneralInformation generalInformation, EconomicActivity economicActivity,
			FinancialInformation financialInformation, PEP pep, Authorization authorization, int active,
			String description, String notice, LocalDateTime dateTime, DateTimeFormatter dtformat, String dateSave) {
		super();
		this.id = id;
		this.identification = identification;
		this.numberId = numberId;
		this.cognitoId = cognitoId;
		this.expeditionDate = expeditionDate;
		this.names = names;
		this.lastName = lastName;
		this.cellphone = cellphone;
		this.gender = gender;
		this.email = email;
		this.habeas = habeas;
		this.tyc = tyc;
		this.signature = signature;
		this.generalInformation = generalInformation;
		this.economicActivity = economicActivity;
		this.financialInformation = financialInformation;
		this.pep = pep;
		this.authorization = authorization;
		this.active = active;
		this.description = description;
		this.notice = notice;
		this.dateTime = dateTime;
		this.dtformat = dtformat;
		this.dateSave = dateSave;
	}

	@Override
	public String toString() {
		return "BasicInformation [id=" + id + ", identification=" + identification + ", numberId=" + numberId
				+ ", cognitoId=" + cognitoId + ", expeditionDate=" + expeditionDate + ", names=" + names + ", lastName="
				+ lastName + ", cellphone=" + cellphone + ", gender=" + gender + ", email=" + email + ", habeas="
				+ habeas + ", tyc=" + tyc + ", signature=" + signature + ", generalInformation=" + generalInformation
				+ ", economicActivity=" + economicActivity + ", financialInformation=" + financialInformation + ", pep="
				+ pep + ", authorization=" + authorization + ", active=" + active + ", description=" + description
				+ ", notice=" + notice + ", dateTime=" + dateTime + ", dtformat=" + dtformat + ", dateSave=" + dateSave
				+ "]";
	}



	

}
