package co.approbe.award.lambda;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "logAward")
public class Log {
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String id;
	@DynamoDBAttribute
	private String information;
	LocalDateTime dateTime = LocalDateTime.now();
	DateTimeFormatter dtformat = DateTimeFormatter.ofPattern("dd/MM/yyyy hh:mm:ss");
	@DynamoDBAttribute
	private String dateSave = dateTime.format(dtformat);
	
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getInformation() {
		return information;
	}
	public void setInformation(String information) {
		this.information = information;
	}
	
	public String getDateSave() {
		return dateSave;
	}
	public void setDateSave(String dateSave) {
		this.dateSave = dateSave;
	}
	public Log() {
		super();
	}
	public Log(String id, String information, LocalDateTime dateTime, DateTimeFormatter dtformat, String dateSave) {
		super();
		this.id = id;
		this.information = information;
		this.dateTime = dateTime;
		this.dtformat = dtformat;
		this.dateSave = dateSave;
	}
	
	
}
